version: "3"

networks:
  h-app:
    driver: bridge

services:
  mysql: #mysql容器
    image: mysql:8
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "TZ=Asia/Shanghai"
      - "LANG=en_US.UTF-8"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}" #这里自行设置root用户的密码
    volumes:
      - "/opt/app/mysql/my.cnf:/etc/mysql/my.cnf"
      - "/opt/app/mysql/data:/var/lib/mysql"
    ports:
      - "9501:3306"  #宿主机和容器间的端口映射，可自行配置
    networks:
      - h-app

  redis:
    image: redis
    container_name: redis
    restart: always
    hostname: redis
    privileged: true
    ports:
      - "9500:6379"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - "/opt/app/redis/conf:/data/redis/conf"
      - "/opt/app/redis/data:/data/redis/data"
      - "/opt/app/redis/logs:/data/redis/logs"
    command: "redis-server /data/redis/conf/redis.conf"
    networks:
      - h-app

  htwinkle.cn.web:
    image: registry.cn-hangzhou.aliyuncs.com/htwinkle/htwinkle.cn.web
    container_name: htwinkle.cn.web
    ports:
      - "9011:9011"
    environment:
      - "TZ=Asia/Shanghai"
      - "LANG=en_US.UTF-8"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - "/opt/htwinkle.cn.web/web/log/:/opt/hwinkle.cn.web/web/log/"
    networks:
      - h-app
    depends_on:
      - mysql
      - redis